### ISSUE TITLE
Art.113

### ISSUE THREAD

**Issue by Testato** [zacchiro/costituzione#13]
il 113 non e' stato modificato, mentre invece risulta presente nella diff

**Comment by loreb** [comment]
Mea culpa, nth-article separa gli articoli in modo semplicistico e quindi è convinto che "Titolo V etc" sia la conclusione dell'articolo 113

Salvo complicazioni sistemo dopo cena
(PS grazie)

**Comment by loreb** [comment]
La patch qui di sotto sistema il problema (per inciso visibile anche in altri articoli adiacenti a "Sezione N" etc)

diff(1)ando il risultato prima e dopo la cura mi sembra tutto a posto;
se mi è sfuggito qualcosa, fatemi sapere.

diff --git i/bin/nth-article w/bin/nth-article
index d8673f5..2633a2d 100755
--- i/bin/nth-article
+++ w/bin/nth-article
@@ -16,17 +16,16 @@ BEGIN {
     found=0
 }

-# Find the right article
+# Find the right article - see issue 13!
+# "##### Art. 113. (blah blah)
+#  ### Titolo V"
+# ==> lines beginning with "#" are a boundary, those with "Art." begin articles
+/^##*/ { if(found) exit }
 $2 == "Art." {
     if($3 == article) {
         found=1
-    } else {
-        if(found) {
-            exit
-        }
   }
  }

-# every line
 { if(found) print }
 ' "$input"

**Comment by Testato** [comment]
Prova a mergiarlo, così controllo

**Comment by loreb** [comment]
Il repo non è mio :)

X provare, il contenuto finale di bin/nth-script è

```
#! /bin/sh
# $0 3 xx.md => print article 3 from xx.md
test $# -eq 2 || { echo >&2 "Usage: $0 N FILE" ; exit 100 ; }
article="$1"
input="$2"

case x"$article" in
    (*.*) ;;
    (*)
    article="$article". # Format: "### Art. 42."
    ;;
esac

exec awk -v article="$article" '
BEGIN {
    found=0
}

# Find the right article - see issue 13!
# "##### Art. 113. (blah blah)
#  ### Titolo V"
# ==> lines beginning with "#" are a boundary, those with "Art." begin articles
/^##*/ { if(found) exit }
$2 == "Art." {
    if($3 == article) {
        found=1
    }
}

{ if(found) print }
' "$input"
```

**Comment by zacchiro** [comment]
On Fri, Nov 18, 2016 at 01:07:53PM -0800, Lorenzo Beretta wrote:

> La patch qui di sotto sistema il problema (per inciso visibile anche
> in altri articoli adiacenti a "Sezione N" etc)

Grazie Lorenzo, fix applicato e problema risolto!
