### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by loreb** [zacchiro/costituzione#14]
"I loro rapporti sono olati dai Patti Lateranensi" :)

(trovata diffando rispetto alla versione sul sito credo del senato, per cui non dovrebbero essercene altri)

**Comment by zacchiro** [comment]
On Mon, Nov 28, 2016 at 01:00:37PM -0800, Lorenzo Beretta wrote:
> "I loro rapporti sono olati dai Patti Lateranensi" :)

Pull request, please? :)

-- 
Stefano Zacchiroli . zack@upsilon.cc . upsilon.cc/zack . . o . . . o . o
Computer Science Professor . CTO Software Heritage . . . . . o . . . o o
Former Debian Project Leader . OSI Board Director  . . . o o o . . . o .
« the first rule of tautology club is the first rule of tautology club »

**Comment by loreb** [comment]
Fatta.

PS
Lo script per il #9 ha problemi o avendo già votato ti stai disintossicando da queste cose?

**Comment by zacchiro** [comment]
On Mon, Nov 28, 2016 at 03:09:38PM -0800, Lorenzo Beretta wrote:
> Lo script per il #9 ha problemi o avendo già votato ti stai
> disintossicando da queste cose?

Anche quella non è una pull request, quindi verificare/testare/etc
richiede più sbattimento da parte mia. E visto che il problema è minore
senza un vero impatto sui contenuti, la bilancia sbattimento/beneficio
non ha mai superato la soglia necessaria :) Se mi converti anche quello
in pull request, aumentano fortemente les chances che ci guardi prima
del voto.

Grazie!
-- 
Stefano Zacchiroli . zack@upsilon.cc . upsilon.cc/zack . . o . . . o . o
Computer Science Professor . CTO Software Heritage . . . . . o . . . o o
Former Debian Project Leader . OSI Board Director  . . . o o o . . . o .
« the first rule of tautology club is the first rule of tautology club »

**Comment by zacchiro** [comment]
Closed in #15
