### ISSUE TITLE
Parti del nuovo art 70 sembrano appartenere al 72 nella diff

### ISSUE THREAD

**Issue by loreb** [zacchiro/costituzione#6]
```
$ cd diff&&make&&fgrep Art. *md|sort -n|uniq -c|sort -n|tail
2 ##### Art. 71.
2 ##### Art. 72.
# In alternativa...
$ fgrep Art. *md | grep -C4 70
# risultato: 66,67,68,69,70,71,72,71,72
```

Col risultato che le aggiunte all'articolo 70 sembrano parte del 72.
Usando diff(1) il problema scompare, ma non avendo nessuna familiarità con wdiff(1)
non so  quanto la cosa sia rilevante.

PS
"Art. 68. 9"

PPS
Grazie per il progetto!!

**Comment by zacchiro** [comment]
On Thu, Jul 07, 2016 at 08:23:02AM -0700, Lorenzo Beretta wrote:

> ```
> $ cd diff&&make&&fgrep Art. *md|sort -n|uniq -c|sort -n|tail
> 2 ##### Art. 71.
> 2 ##### Art. 72.
> # In alternativa...
> $ fgrep Art. *md | grep -C4 70
> # risultato: 66,67,68,69,70,71,72,71,72
> ```
> 
> Col risultato che le aggiunte all'articolo 70 sembrano parte del 72.
> Usando diff(1) il problema scompare, ma non avendo nessuna familiarità con wdiff(1)
> non so  quanto la cosa sia rilevante.

Yep, il problema purtroppo è noto, ma non ho ancora avuto tempo di
risolverlo come si deve :( Il punto è che qua vogliamo veramente diff
contestuali, articolo per articolo. Un diff che si "sporga" da un
articolo all'altro non ha senso.

Quindi quello che bisognerebbe fare è una prima passata che divida la
costituzione in articoli, e poi usi wdiff articolo-per-articolo, unendo
i risultati in un unico output.

Non avrò tempo di lavorarci nelle prossime settimane purtroppo, ma patch
in questo senso sono più che benvenute :-)

> PS
> "Art. 68. 9"

?

## 

Stefano Zacchiroli  . . . . . . .  zack@upsilon.cc . . . . o . . . o . o
Maître de conférences . . . . . http://upsilon.cc/zack . . . o . . . o o
Former Debian Project Leader . . . . . @zacchiro . . . . o o o . . . o .
« the first rule of tautology club is the first rule of tautology club »

**Comment by loreb** [comment]
"Art. 68. 9" anzichè "Art. 68" nella versione del 2012:
`$ diff  ../2012-04-20/costituzione.md ../2016-01-20/costituzione.md|fgrep -i art.`

Prima parte della patch, uno script che estrae solamente l'articolo n-esimo
(mai fatto una PR in vita mia; imparare potrebbe essere un proposito per l'estate, ma è quasi ora di cena...)

```
#! /bin/sh
# $0 3 xx.md => print article 3 from xx.md
test $# -eq 2 || { echo >&2 "Usage: $0 n doc" ; exit 100 ; }
article="$1"
input="$2"

case x"$article" in
        (*.*) ;;
        (*)
                article="$article". # Format: "### Art. 42."
                ;;
esac

exec awk -v article="$article" '
BEGIN {
        found=0
}

# Find the right article
$2 == "Art." {
        if($3 == article) {
                found=1
        } else {
                if(found) {
                        exit
                }
        }
}

# every line
{ if(found) print }
' "$input"
```

**Comment by loreb** [comment]
Seconda parte, uno script che lista (per numero) gli articoli (hai visto mai)

```
#! /bin/sh
# Usage: $0 [file.md]
# Usage: cat ... | $0
case $# in
        (0) ;;
        (1) exec <"$1" || exit;;
        (*) echo>&2 "usage: $0 file"; exit 100;;
esac
exec awk '$2 == "Art." { print $3 }'
```

**Comment by loreb** [comment]
Scritto molto in fretta e furia, sorry ;)

```
#! /bin/bash
# NEEDS BASH for "<( ... )"
test $# -eq 2 || { echo>&2 "Usage: $0 file1 file2"; exit 100; }
for i ; do
        test -e "$i" || exec ls "$i"
done
for article in $(cat "$1" "$2" | ./listarticles | sort -n | uniq) ; do
        # unchanged => skip
        cmp -s <(./ntharticle $article "$1") <( ./ntharticle $article "$2") && continue
        # add options etc to wdiff!
        wdiff <(./ntharticle $article "$1") <( ./ntharticle $article "$2")
done
```

**Comment by zacchiro** [comment]
Eccomi. Chiedo venia per il ritardo ma sono ora di ritorno e attivo per correggere questo problema.
Ho integrato nel nuovo branch feature/diff-by-article i cambiamenti di @loreb. Facendo checkout e make in quel branch si vede il nuovo risultato.

Il problema originale di pezzi di modifiche che "migrano" da un articolo all'altro è risolto.
Ma sono presenti altri glitch. In particolare, alcune scritte "abrogato" sembrano fuori posto, mentre alcuni heading di articolo presentano un trailing ".N" (dove "N" è un digit).

Non ho ancora avuto tempo di debuggare il problema.
@loreb: hai tempo/voglia di verificare cosa succede nel nuovo branch?
Una volta risolto il problema sarò ben lieto di integrare il tutto in master.

Grazie!

**Comment by loreb** [comment]
Scusa la mancata pr, ne ho fatta una di prova con un altro repo e aspettavo di vedere se ho fatto casino, ma mi sa che è andato in vacanza :)

Riguardo l'abrogato, direi tag innestati male: 

```
<p><span class="delete">I senatori sono eletti a suffragio universale e diretto dagli elettori che
hanno superato il venticinquesimo anno di età.</p>

<p>Sono eleggibili a senatori gli elettori che hanno compiuto il quarantesimo
anno.</span></p>
```

Nota bene: apro p, apro span, CHIUDO il p di prima, apro un altro p, chiudo lo span, chiudo p
Idem eg l'articolo 99: il markdown è corretto, ma nella trasformazione in html inserisce `<p>` e `</p>` a ogni riga e questo interferisce con `<span>`.
Sul come risolvere, dovrei pensarci.

Per quel che riguarda il .N, se intendi tipo l'articolo 68 è quello che intendevo col mio criptico "Art. 68. 9" - c'è scritto cosi in 2012-04-20/costituzione.md, se invece è altro non ho capito.

PS
bin/html-wdiff non è eseguibile, chmod +x

**Comment by zacchiro** [comment]
On Wed, Aug 17, 2016 at 09:09:38AM -0700, Lorenzo Beretta wrote:

> Riguardo l'abrogato, direi tag innestati male: 

Nice catch, questo è esattamente il problema. Ed è comprensibile perché
la sintassi di Markdown non "commuta" (nel senso categorico del termine)
con quella HTML.

Una soluzione quasi corretta è quella di passare --avoid-wraps a wdiff.
Ho provato e sembra risolvere il problema.

È solo "quasi" corretta nel senso che produce molti <span>..</span> in
più di quelli che servono, anche consecutivi. Penso che per renderli
completa basti aggiungere una passata di sed multiline che rimuova
sequenze "</span>NEWLINE<span>" a patto che ci sia _un_ solo newline,
altrimenti ricaschiamo nel problema precedente.  Se hai voglia di
provare: be my guest :-)

> PS
> bin/html-wdiff non è eseguibile, chmod +x

Fatto e pushato, thanks!

## 

Stefano Zacchiroli . zack@upsilon.cc . upsilon.cc/zack . . o . . . o . o
Computer Science Professor . CTO Software Heritage . . . . . o . . . o o
Former Debian Project Leader . OSI Board Director  . . . o o o . . . o .
« the first rule of tautology club is the first rule of tautology club »

**Comment by loreb** [comment]
Bella avoid-wraps, io ieri stavo cercando qualunque cosa per inserire (qualcosa equivalente a)i vari span usando la sintassi di markdown, oppure (come ultima disperata risorsa) un tag html aggiuntivo che evitasse il problema (e alcuni quasi funzionavano...)

Per gli span... un primo tentativo in fretta e furia (e in awk) è andato cosi cosi, nel senso che per ora è bacato.
Magari vedrò dopo cena con più calma.

**Comment by loreb** [comment]
Non perfetto, ma è un inizio:

``` awk
#! /usr/bin/awk -f
# XXX may be "/bin/awk", use "awk -f" EXPLICITLY!

function flush() {
        if(!buffered) {
                return
        }
        printf("<span class=\"%s\">", currentclass)
        currentclass = ""
        for(i = 0; i < buffered; i++) {
                print bufferedlines[i]
        }
        buffered = 0
        print "</span>"
}

function push(line) {
        sub("^<span[^>]*>", "", line)
        sub("</span>$", "", line)
        bufferedlines[buffered++] = line
}

function newspan(class, line) {
        # crap. multiple <span> on a single line?
        # XXX TODO improve! (eg: Art55)
        if(match(line, "<span.*<span") > 0) {
                flush()
                print
                return
        }
        # no.
        if (class == currentclass) {
                push(line)
                return
        }
        flush()
        currentclass = class
        push(line)
}

/^<span class="delete">.*<\/span>/ { newspan("delete", $0); next }
/^<span class="insert">.*<\/span>/ { newspan("insert", $0); next }

# default: just print
{ flush(); print }

END {
        flush()
}
```

**Per ora** prende solo il caso più semplice, cioè "(inizio riga)<span>...</span>(fine riga)",
e fallisce stupidamente eg con l'articolo 63; se muori dalla voglia di correggerlo o riscriverlo in sed,
fa pure, altrimenti lo riprendo domani o dopo.

Per la cronaca, il famoso bug era

``` awk
/^<span class="delete">.*<\/span>/ { newspan("insert", $0); next }
/^<span class="insert">.*<\/span>/ { newspan("delete", $0); next }
```

mai scrivere a stomaco vuoto!

**Comment by zacchiro** [comment]
Rieccomi.

On Thu, Aug 18, 2016 at 02:42:22PM -0700, Lorenzo Beretta wrote:

> **Per ora** prende solo il caso più semplice, cioè "(inizio
> riga)<span>...</span>(fine riga)", e fallisce stupidamente eg con
> l'articolo 63; se muori dalla voglia di correggerlo o riscriverlo in
> sed, fa pure, altrimenti lo riprendo domani o dopo.

In breve, ho risolto questo problema, applicando un approccio (a mio
avviso) più semplice, vedi commit su master. Visto che lo stato attuale
mi sembra più che soddisfacente, ho anche rebuildato il sito statico
(http://zacchiro.github.io/costituzione/) e messo link diretti a li
venendo da README.md.

Restano un paio di issues, che cito qua ma meriterebbero bug report
separati:
- per essere un vero "inline" diff, dovremmo includere in toto anche gli
  articoli non modificati. Puoi dare un'occhiata al meccanismo di
  list-articles per farlo?
- l'articolo 68 qui
  http://zacchiro.github.io/costituzione/diff/2012-04-20/2016-01-20 ,
  appare con un trailing ".9", marcato come cancellato (il che
  ovviamente è falso). Idee di da dove venga questo refuso?
- alcuni diff hanno tuttora newline spuri, come per esempio "Il
  regolamento stabilisce<A CAPO>". Idee?

Grazie per i tuoi contributi, non saremmo mai arrivati a questo punto
senza il tuo stimolo :)

## A presto.

Stefano Zacchiroli . zack@upsilon.cc . upsilon.cc/zack . . o . . . o . o
Computer Science Professor . CTO Software Heritage . . . . . o . . . o o
Former Debian Project Leader . OSI Board Director  . . . o o o . . . o .
« the first rule of tautology club is the first rule of tautology club »

**Comment by loreb** [comment]
Intanto scusa la scomparsa, sono stato occupato per due/tre giorni e mi era uscito di mente.
Andando in ordine:

> In breve, ho risolto questo problema, applicando un approccio (a mio avviso) più semplice, vedi commit su master.

grande!

> - per essere un vero "inline" diff, dovremmo includere in toto anche gli articoli non modificati. Puoi dare un'occhiata al meccanismo di list-articles per farlo?

Colpa mia, avevo capito che volevi solo le modifiche, sorry.
In diff-by-article, `cmp -s <( nth-article $article "$1" ) <( nth-article $article "$2" ) && continue
`
cioè "if(articolo non modificato) continue; else diff", basta rimpiazzare il "continue" con `nth-article $article "$1" (oppure $2 visto che sono uguali)`

Per la cronaca (è il rischio nell'accettare contributi: se non l'hai scritto tu, ti è poco familiare... potevi bacchettarmi prima di accettarlo),  ls-articles non fa altro che listare gli articoli per numero, casomai ne venisse aggiunto o tolto qualcuno.
E qui devo bacchettarti io, perchè avevo scritto
`for article in $(cat "$1" "$2" | ./listarticles | sort -n | uniq) ; do`, e tu hai perso per strada "sort -n | uniq", col risultato che gli articoli sono stampati due volte.
ls-articles è molto banale, stampa il numero di tutti gli articoli che vede nello standard input, per cui
cat originale nuova|ls-articles stampa due volte tutti gli articoli presenti in entrambe :)

> - l'articolo 68 qui
>   è quello che ho cercato di scrivere non so quante volte, apri 2012-04-20/costituzione.md alla riga quattrocentosettantanove e preparati per un bel "doh!" ;p
> - alcuni diff hanno tuttora newline spuri, come per esempio "Il regolamento stabilisce<A CAPO>". Idee?

Stavo per scrivere che è ovvio, leggendo i due articoli:
- "il regolamento stabilisce procedimenti" # originale
- "(nuovo paragrafo con "a capo") I regolamenti stabilicono procedimenti"

... ma in effetti mi aspetterei "<del>il regolamento</del><ins>(nuovo paragrafo etc)</ins> procedimenti"
Così a naso direi che il mio modello mentale di come funziona wdiff non corrisponde alla realtà,
e se è così devo documentarmi prima di scrivere qualcosa di sensato (prima di vedere questo
progetto non sapevo nemmeno che esistesse)
Ci sono altri casi dello stesso problema?

> Grazie

Grazie a te invece! Stavo cercando il testo originale e nuovo in formato testuale, con l'incubo di dover costruire a manina quello nuovo dal modo assurdo in cui scrivono le leggi e la vocina della coscienza che mi diceva "reproducible builds! fai uno script che produca diosolosacome i due testi a partire da qualcosa di liberamente scaricabile!"... poi meno male che ho trovato il tuo lavoro.

PS
Ora che ci faccio caso, uso quasi solo debian da quando sarge era stable (e allegata a una rivista, avevo una 56k); grazie anche/soprattutto per quello.

**Comment by loreb** [comment]
Mi è presa la curiosità mentre spulciavo "info wdiff", bashismi gratuiti:

``` bash
wdiff <(echo uno due) <(echo 1 due)
```

``` bash
wdiff <(echo titolo; echo uno due) <(echo titolo; echo 1 due)
```

e inserendo una riga vuota, come nel nostro testo:

``` bash
wdiff <(echo titolo; echo;echo uno due) <(echo titolo; echo;echo 1 due)
```

Sono io o la cosa ha pochissimo senso?

**Comment by zacchiro** [comment]
On Thu, Sep 01, 2016 at 01:41:10PM -0700, Lorenzo Beretta wrote:

> > - per essere un vero "inline" diff, dovremmo includere in toto anche gli articoli non modificati. Puoi dare un'occhiata al meccanismo di list-articles per farlo?

Alla fine, ritiro questa proposta. L'ho testata con vari utenti
potenziali, ed invariabilmente mi hanno tutti risposto che l'approccio
attuale è migliore in quanto più focused su cosa è attualmente
cambiato. Per chi vuole vedere i testi completi (e non modificati) degli
altri articoli, ho aggiunto link ai fulltext nei titoli delle pagine
diff.

> `for article in $(cat "$1" "$2" | ./listarticles | sort -n | uniq) ; do`, e tu hai perso per strada "sort -n | uniq", col risultato che gli articoli sono stampati due volte.

Diciamo piuttosto che questo è ciò che succede a copia-incollare
modifiche proposte in mail e non come patch "git am" oppure come pull
requests...

> > - l'articolo 68 qui
> 
> è quello che ho cercato di scrivere non so quante volte, apri
> 2012-04-20/costituzione.md alla riga quattrocentosettantanove e
> preparati per un bel "doh!" ;p

D'oh! (corretto, grazie)

> Così a naso direi che il mio modello mentale di come funziona wdiff non corrisponde alla realtà,
> e se è così devo documentarmi prima di scrivere qualcosa di sensato (prima di vedere questo
> progetto non sapevo nemmeno che esistesse)
> Ci sono altri casi dello stesso problema?

Questi tutti quelli che trovo a
http://zacchiro.github.io/costituzione/diff/2012-04-20/2016-01-20
- art 61
- art 67
- art 72 (2 occorrenze)
- art 78
- art 80
- art 81
- art 82

non vedo un pattern evidente.

## Ciao

Stefano Zacchiroli . zack@upsilon.cc . upsilon.cc/zack . . o . . . o . o
Computer Science Professor . CTO Software Heritage . . . . . o . . . o o
Former Debian Project Leader . OSI Board Director  . . . o o o . . . o .
« the first rule of tautology club is the first rule of tautology club »

**Comment by loreb** [comment]
> non vedo un pattern evidente.

Vedo il mio post perplesso di ieri sera e rilancio di

``` bash
wdiff  <(echo uno due) <(echo 1 due)
wdiff  <(echo primariga; echo uno due) <(echo primariga; echo 1 due)
wdiff <(echo titolo; echo;echo zero uno due) <(echo titolo; echo;echo zero 1 due)
```

Correggimi se sbaglio, ma pare che wdiff aggiunga un newline extra se c'è una riga di cui viene modificata la parte iniziale

---

edit: anche nel caso di
`wdiff  <(echo primariga; echo uno) <(echo primariga; echo 1)`

Andando a naso, immagino che... ritiro quello che stavo per scrivere, e ri-rilancio di
`wdiff  <(echo primariga; echo uno due tre) <(echo primariga; echo 1 due 3)`

Pensavo che vista la differenza iniziale le avrebbe considerate righe distinte, invece mette
separato il cambio iniziale e gestisce "normalmente" quello finale.

Euristica sballata?

**Comment by loreb** [comment]
Pare sia un problema noto di wdiff -- https://savannah.gnu.org/bugs/?40063

Magari investigo, ma non faccio promesse stavolta

**Comment by zacchiro** [comment]
On Fri, Sep 02, 2016 at 09:30:32AM -0700, Lorenzo Beretta wrote:

> Pare sia un problema noto di wdiff -- https://savannah.gnu.org/bugs/?40063

Nice catch!

Ho aperto una issue separata a proposito di questo
https://github.com/zacchiro/costituzione/issues/9 , nella quale ipotizzo
anche una soluzione (o meglio: un workaround). Se ti piace, patches
welcome :-)

## 

Stefano Zacchiroli . zack@upsilon.cc . upsilon.cc/zack . . o . . . o . o
Computer Science Professor . CTO Software Heritage . . . . . o . . . o o
Former Debian Project Leader . OSI Board Director  . . . o o o . . . o .
« the first rule of tautology club is the first rule of tautology club »
