### ISSUE TITLE
extra newlines in diffs (due to upstream wdiff bug)

### ISSUE THREAD

**Issue by zacchiro** [zacchiro/costituzione#9]
Due to [wdiff bug 40063](https://savannah.gnu.org/bugs/?40063), there are a number of extra newlines in the diffs, some examples from [riforma Boschi diff](http://zacchiro.github.io/costituzione/diff/2012-04-20/2016-01-20):
- Art 61: Le elezioni delle nuove Camere hanno NEWLINE
- Art 67: Ogni membro NEWLINE
- Art 72: Il regolamento stabilisce NEWLINE
- Art 72: Può NEWLINE
- Art 78: Le Camere deliberano NEWLINE
- Art 80: Le Camere autorizzano NEWLINE
- Art 81: Le camere NEWLINE
- Art 82: Ciascuna NEWLINE

[ hat tip to @loreb for matching this issue to upstream wdiff bug ]

**Comment by zacchiro** [comment]
It looks like the following heuristic would work as a workaround to this issue.
- remove a newline when the following conditions are _all_ met:
  1. the newline follows an ins or del block
  2. the ins/del block does not end with a '.'
  3. the newline precedes a matching block (i.e., ins-NEWLINE-del or del-NEWLINE-ins)

(3) seems actually optional in the above examples, but I'm not yet clear about what are the consequences of leaving it out (or in).

**Comment by loreb** [comment]
Scusa il ritardo cosmico - una parte di me "voleva" sistemare il bug di wdiff,
ma il codice è abbastanza scoraggiante, e ammetto di non averci + pensato
finchè provando bashonwindows (che usa Ubuntu 14.04.4 LTS!)
mi sono reso conto che comunque un eventuale bugfix sarebbe arrivato alle distro
a referendum concluso...

``` sh
#! /bin/sh
# Usage: $0 buggy.md >fixed.md
test $# -eq 1 || { echo>&2 "Usage: $0 issue9.md >fixed.md"; exit 100; }
# grep '\r'? no...
cat "$1" | tr -d '\r' | cmp - "$1" || {
        echo>&2 'This hack requires no \\r in the input, convert newlines'
        exit 100
}
exec <"$1" || exit
# HACK from https://unix.stackexchange.com/a/152389
# since the proper solution is, well...
tr '\n' '\r' | \
        sed 's,\([^.]\)</del>\r\r<ins>,\1</del><ins>,g' | \
        sed 's,\([^.]\)</ins>\r\r<del>,\1</ins><del>,g' | \
        tr '\r' '\n'
```

Fare la sostituzione multiline a quanto pare è abbastanza rognoso, con o senza perl,
per cui mi sono affidato a stackoverflow come da commento;
controllare che il file di partenza non contenga \r è stupidamente complicato anche lui,
per cui lo verifico controllando che cancellare \r non cambia nulla.

A occhio ("cd diff && make && ./issue9 *md |diff -u *md -|less") sembra che funzioni;
in caso di problemi fammi sapere, prometto risposte con tempi meno geologici.

**Comment by loreb** [comment]
ping?

**Comment by loreb** [comment]
Le mie scuse per la mancata pr, sinceramente non sapevo che facesse una simile differenza.
